### PR TITLE
Attempt to avoid rare fails in redirect.t

### PR DESCRIPTION
**Pull request by johannessen**
See https://github.com/libwww-perl/libwww-perl/issues/370#issuecomment-859909166 for discussion.

### CODE REVIEW

**Review by oalders — DISMISSED** [review]
Thanks, @johannessen!

**Comment by oalders** [comment]
@johannessen could you add the following to `Changes` so that the build can run?

```
$ git diff
diff --git a/Changes b/Changes
index d8a25db5..8fe56d27 100644
--- a/Changes
+++ b/Changes
@@ -1,6 +1,7 @@
 Change history for libwww-perl

 {{$NEXT}}
+    - Attempt to avoid rare fails in redirect.t (GH#380) (Arne Johannessen)

 6.54      2021-05-06 17:53:56Z
     - Be explicit in the prerequisite of HTTP::Status (GH#378) (Max Maischein)
 ```

**Comment by johannessen** [comment]
Right, sorry about that!

**Review by oalders — APPROVED** [review]
👍

**Comment by johannessen** [comment]
Oops … once more, now without the leading `+` from the patch.

**Review by oalders — APPROVED** [review]
👍

**Comment by johannessen** [comment]
Thank you for your patience!

**Comment by oalders** [comment]
@johannessen sorry about that! Ideally I'd just create the Changelog myself on release and you wouldn't have to bother with it. :) I've just uploaded to CPAN. Thanks for this!

**Pull request merged**
