### PR TITLE
Be explicit in the prerequisite of HTTP::Status

### PR DESCRIPTION
**Pull request by Corion**
See https://perlmonks.org/?node_id=11132138 , which is weird code
and shouldn't fail, but maybe fails in persistent environments
like Apache.

### CODE REVIEW

**Review by karenetheridge — APPROVED** [review]
Since LWP::UserAgent is using constants from HTTP::Status, it should definitely make sure it's loaded first.

**Comment by petdance** [comment]
Big 👍 to not relying on other modules bringing in the modules you need.

**Comment by oalders** [comment]
This has new been released to CPAN.

**Comment by rubberduck3000** [comment]
Hi!

Hope I just got an old version but still got this error in

package LWP::UserAgent;

use strict;

use parent qw(LWP::MemberMixin);

use Carp ();
use File::Copy ();
use HTTP::Request ();
use HTTP::Response ();
use HTTP::Date ();

use LWP ();
use HTTP::Status ();
use LWP::Protocol ();

use Scalar::Util qw(blessed openhandle);
use Try::Tiny qw(try catch);

our $VERSION = '6.67';


Just add quotes to /usr/share/perl5/LWP/UserAgent.pm

    my $code = $response->code;

    if (   $code == HTTP::Status::RC_MOVED_PERMANENTLY
        or $code == HTTP::Status::RC_FOUND
        or $code == HTTP::Status::RC_SEE_OTHER
        or $code == HTTP::Status::RC_TEMPORARY_REDIRECT
        or $code == HTTP::Status::RC_PERMANENT_REDIRECT)

Like this

    my $code = $response->code;

    if (   $code == "HTTP::Status::RC_MOVED_PERMANENTLY"
        or $code == "HTTP::Status::RC_FOUND"
        or $code == "HTTP::Status::RC_SEE_OTHER"
        or $code == "HTTP::Status::RC_TEMPORARY_REDIRECT"
        or $code == "HTTP::Status::RC_PERMANENT_REDIRECT)"

**Comment by oalders** [comment]
@rubberduck3000 did you 

`use HTTP::Status ();` in your code sample? I can't tell as it's incomplete.

**Pull request merged**
