### PR TITLE
improve handler documentation

### LINKED ISSUE #272: Documentation around `add_handler` needs clarification
The docs look like `response_data => sub { my($response, $ua, $h, $data) = @_; ... }`

My immediate thought when seeing the docs is that `$h` is an `HTTP::Headers` object, but it appears to actually be a handler:

```perl
sub run_handlers {
    my($self, $phase, $o) = @_;
    if (defined(wantarray)) {
        for my $h ($self->handlers($phase, $o)) {
            my $ret = $h->{callback}->($o, $self, $h);
            return $ret if $ret;
        }
        return undef;
    }
 
    for my $h ($self->handlers($phase, $o)) {
        $h->{callback}->($o, $self, $h);
    }
}
```

### PR DESCRIPTION
**Pull request by simbabque**
fixes #272

### CODE REVIEW

**Comment by genio** [comment]
Looks good to me! Thank you for this. 

I’m on my phone so I can’t check at the moment but please ensure the C<< style POD renders correctly. I want to say there needs to be a white space between them and the content within for some reason.

**Comment by simbabque** [comment]
I'm always unsure about those. It might be wrong indeed. Is there a good
way to test this locally?

**Comment by oalders** [comment]
Could you just run it through `perldoc`?

**Comment by genio** [comment]
I usually just do a quick visual inspection using `perldoc lib/LWP/UserAgent.pm` and scroll through to the area to ensure it looks correct. Not a great method, but it works (tm).

**Comment by simbabque** [comment]
I'll do that later or tomorrow, then update. Wait with the merge please.
Sorry about that.

**Comment by simbabque** [comment]
Ok, fixed.

**Comment by simbabque** [comment]
The failed test is a release-only test.

> xt/release/changes_has_content.t ....... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests 

I don't think this test should be run on PRs. It seems to happen with all PRs at the moment.

**Comment by karenetheridge** [comment]
> I don't think this test should be run on PRs. It seems to happen with all PRs at the moment.

Yes, it very much should. Every pull request should have a high level (user-oriented) description of the change, as well as attribution in the form the author prefers.  This makes the release process much smoother.

**Comment by karenetheridge** [comment]
please rebase against the new master (when you come back to this) and `git push --force` -- thanks!

**Comment by simbabque** [comment]
Let me just add Changes... forgot about that.

**Comment by simbabque** [comment]
There we go. All ready to merge. :)

**Comment by oalders** [comment]
Thanks @simbabque!

**Pull request merged**
