### PR TITLE
Remove LWP::Protocol::GHTTP

### PR DESCRIPTION
**Pull request by katkad**
because HTTP::GHTTP is obsoleted by obsolete libghttp

If you happen to remove LWP::Protocol::GHTTP according to https://github.com/libwww-perl/libwww-perl/issues/80 you can use this pull request.

### CODE REVIEW

**Comment by karenetheridge** [comment]
I think this one is @gisle's call.

**Comment by gisle** [comment]
I would not mind if it was unbundled from libwww-perl, but I then think `LWP::Protocol::GHTTP` ought to have its own dist on CPAN in case anybody actually uses it.  The `HTTP::GHTTP` module is still present.

**Comment by genio** [comment]
```HTTP::GHTTP``` needs to be updated as it fails to install due to outdated locations for the library itself.

**Comment by genio** [comment]
https://github.com/genio/lwp-protocol-ghttp

@gisle Can you review that and see what you think as a possible separate dist?

**Comment by gisle** [comment]
Looks good to me.

**Comment by genio** [comment]
@gisle Great!  If you want to release it so that it's easier to keep up with the rest of the libwww module set, please feel free to do so.  I have no strong feelings about doing so myself as all I have done is basically just package it up and add a test set.  On the other hand, if you prefer I do it, please let me know.

**Comment by gisle** [comment]
I'm lazy — so I prefer if you do it. :-)

**Comment by genio** [comment]
@karenetheridge I've scheduled my unauthorized push to the CPAN for deletion.  Sorry about being a bit click-happy and publishing without first thinking about PAUSE permissions.  Please let me know if you need anything from me in order to take over the github repo, etc.

**Comment by genio** [comment]
[LWP::Protocol::GHTTP](https://metacpan.org/pod/LWP::Protocol::GHTTP) has been released and should be able to be safely removed from this dist now.

**Comment by genio** [comment]
Thanks, @katkad

**Pull request merged**
