### PR TITLE
travis shouldn't run release tests for pull requests

### PR DESCRIPTION
**Pull request by simbabque**
This is trying to fix the failing travis builds for pull requests. Please ignore until it's working.

### CODE REVIEW

**Comment by genio** [comment]
This can be corrected by updating the changes file after a release to include a single line with no information:

```
{{$NEXT}}
    - 
```

I think there's value in having the tests run, but we need to ensure they pass after release so that PRs can be tested correctly.

**Comment by genio** [comment]
I updated master. If you rebase your PRs and push, they _should_ pass the xt tests now.

**Comment by simbabque** [comment]
Thanks. I can't do that for a few days. Traveling without computer.
However, shouldn't the next version field be added automatically by another
dzil plugin? Why didn't it?

**Comment by oalders** [comment]
Making the Changes file non-empty but without content could possibly bite me when I run the next release.  That test has caught empty Changes files for me on more than one occasion.  It would be nice to find a solution where this particular test could just get skipped on Travis pull request testing.

**Comment by karenetheridge** [comment]
Release tests shouldn't run for pull requests, but the 'has stuff in Changes' test absolutely *should* run. I'll fix it tonight.

**Comment by karenetheridge** [comment]
Tests are failing for unrelated reasons. It is intentional that pull requests should update the Changes file -- there is code explicitly in dist.ini to add that feature.

**Comment by simbabque** [comment]
> Tests are failing for unrelated reasons. It is intentional that pull requests should update the Changes file -- there is code explicitly in dist.ini to add that feature.

Maybe that could be addressed in the CONTRIBUTING file? It would help future contributors, especially if they are less experienced.

**Pull request closed without merging**
