### PR TITLE
add no_leak.t

### PR DESCRIPTION
**Pull request by skaji**
Add no_leak.t to ensure LWP does not leak variables.
See #296.

### CODE REVIEW

**Comment by karenetheridge** [comment]
This looks great! Using Test::Needs here with a recommended prereq will ensure we don't block installs when the user can't install the extra dependency, but also let us test on as many platforms as we can.

**Comment by petdance** [comment]
Please add a note in the code about what neverssl.com is, in case that site and the explanation of what it is goes away.  This test is going to be around for a long long time.

**Comment by skaji** [comment]
@genio @karenetheridge @petdance Thank you for your reviews.
I added a note about neverssl.com 0cddd0f

**Comment by skaji** [comment]
Now the PR build (not push build) was passed !
screen shot 2018-07-16 at 12 09 52

**Comment by karenetheridge** [comment]
merged, thanks!

**Pull request closed without merging**
