### PR TITLE
Fix Client-Warning: Internal response sometimes reset

### PR DESCRIPTION
**Pull request by augwa**
This fixes issue #171

### CODE REVIEW

**Comment by genio** [comment]
I _think_ I remember us discussing this change quite a while back and it presented problems when the option to not follow redirects at all or only follow 1 redirect or something occurs. I can't remember the details off-hand, but let's test a bit.

**Comment by augwa** [comment]
The problem right now is that if the request was successful within the max number of redirects it will complain that it's an redirect loop, even though it's not redirecting at all.

For instance if you asked for 0 max redirects, then EVERY request will always have this even though it never redirected since the redirect count is currently sitting at 0. therefore 0 >= 0 = true.

**Comment by oalders** [comment]
@augwa would you be able to add some tests to this?

**Comment by simbabque** [comment]
I have reproduced this in the most recent master on version 6.43. I was trying to make a test for it so we can get this merged, but I struggle with where to put that test. All the relevant tests are in t/local/http.t, but that uses the local daemon. That seems the wrong place. At the same time, the generic t/base/ua.t looks like it's utterly the wrong place too, and I don't really want to introduce a new file just for this regression test.

**Comment by oalders** [comment]
I think it's fine to introduce a new file for a regression test. Maybe `t/redirect.t`?

**Pull request closed without merging**
