### PR TITLE
fix lwp-request -C …

### PR DESCRIPTION
**Pull request by fany**
has been broken since commit 82ae34d87f54c51ed7a1c29de54ee7144d736992

### CODE REVIEW

**Comment by karenetheridge** [comment]
Could you please clarify what is broken? What errors do you see?

**Comment by genio** [comment]
Run a server ```morbo server.pl``` in one session:

```perl
#!/usr/bin/env perl
use Mojolicious::Lite;

get '/' => sub {
  my $c = shift;
  warn $c->dumper($c->req->url);
  warn $c->dumper($c->req->headers);
  $c->render(text => 'Hello World!');
};

app->start;
```

Then compare:
```curl -u foo:bar http://localhost:3000``` and
```bin/lwp-request -C foo:bar http://localhost:3000```

During the curl call, the server will output:
```"userinfo" => "foo:bar"```
and
```"authorization" => [ "Basic Zm9vOmJhcg==" ],```
No such properties exist for the lwp-request call.

However, this PR doesn't seem to resolve the issue. Also, I can't seem to find a time where it ever functioned properly according to this test.

@fany Can you please point out where I'm going wrong in this test case? Do you have something that shows the problem?

**Comment by fany** [comment]
When I try to give authentication credentials via `lwp-request -C USERNAME:PASSWORD`,
they are ignored, and I am prompted to enter them interactively, e.g.:

    $ lwp-request -C foo:bar https://service.noris.net/ipacct/
    Enter username for noris network Kundenbereich at service.noris.net:443:

Regards
fany

**Comment by fany** [comment]
> @fany Can you please point out where I'm going wrong in this test case?

LWP::UserAgent will only send the credentials after the server
has returned a 401 Unauthorized.  (AFAIK this is the usual way
HTTP Basic Authentication works.)  So you need a server which
does that to test properly.

I set up an URL to test for you now:
```
fany@homer:~/projects/libwww-perl[master] > bin/lwp-request -C foo:bar https://martin.sluka.de/foobar/
Enter username for lwp-test at martin.sluka.de:443: ^C
fany@homer:~/projects/libwww-perl[master] > git checkout 82ae34d8^
Note: checking out '82ae34d8^'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 1a54bf5... perltidy
fany@homer:~/projects/libwww-perl[(HEAD detached at 1a54bf5)] > bin/lwp-request -C foo:bar https://martin.sluka.de/foobar/
<html><body>Das ist der Rand von Ostermundigen.</body></html>
fany@homer:~/projects/libwww-perl[(HEAD detached at 1a54bf5)] > git branch lwp-request-C
fatal: A branch named 'lwp-request-C' already exists.
fany@homer:~/projects/libwww-perl[(HEAD detached at 1a54bf5)] > bin/lwp-request -C foo:bar https://martin.sluka.de/foobar/
<html><body>Das ist der Rand von Ostermundigen.</body></html>
```
Regards
fany

**Comment by genio** [comment]
@fany Ah, thanks for pointing that out.

This server more accurately mimics that scenario.

```perl
#!/usr/bin/env perl
use Mojolicious::Lite;

get '/' => sub {
  my $c = shift;
  if (!$c->req->headers->header('Authorization')) {
    $c->res->headers->header('WWW-Authenticate'=> 'Basic realm="foobar"');
    $c->render(text=>'You must log in', status => 401);
    return undef;
  }
  warn $c->dumper($c->req->url);
  warn $c->dumper($c->req->headers);
  $c->render(text => 'Hello World!');
};

app->start;
```

With the current master, it does indeed fail to send credentials:
```
git checkout master
bin/lwp-request -C foo:bar http://localhost:3000
```
That will prompt instead of using what was passed in the options.


Using your alteration:
```
git checkout pr/261
bin/lwp-request -C foo:bar http://localhost:3000
```
The credentials are passed as expected.


On an aesthetics note, would moving the class of to the bottom like this look better in the end?
```diff
diff --git a/bin/lwp-request b/bin/lwp-request
index f27648d7..ef57da11 100755
--- a/bin/lwp-request
+++ b/bin/lwp-request
@@ -193,6 +193,7 @@ use URI;
 use URI::Heuristic qw(uf_uri);
 use Encode;
 use Encode::Locale;
+use Getopt::Long;
 
 use HTTP::Status qw(status_message);
 use HTTP::Date qw(time2str str2time);
@@ -217,51 +218,9 @@ my %allowed_methods = (
 
 my %options;
 
-# We make our own specialization of LWP::UserAgent that asks for
-# user/password if document is protected.
-{
-
-    package RequestAgent;
-
-    use strict;
-    use warnings;
-    use base qw(LWP::UserAgent);
-
-    sub new {
-        my $self = LWP::UserAgent::new(@_);
-        $self->agent("lwp-request/$LWP::VERSION ");
-        $self;
-    }
-
-    sub get_basic_credentials {
-        my ($self, $realm, $uri) = @_;
-        if ($options{'C'}) {
-            return split(':', $options{'C'}, 2);
-        }
-        elsif (-t) {
-            my $netloc = $uri->host_port;
-            print STDERR "Enter username for $realm at $netloc: ";
-            my $user = <STDIN>;
-            chomp($user);
-            return (undef, undef) unless length $user;
-            print STDERR "Password: ";
-            system("stty -echo");
-            my $password = <STDIN>;
-            system("stty echo");
-            print STDERR "\n";    # because we disabled echo
-            chomp($password);
-            return ($user, $password);
-        }
-        else {
-            return (undef, undef);
-        }
-    }
-}
-
 my $method = uc(lc($progname) eq "lwp-request" ? "GET" : $progname);
 
 # Parse command line
-use Getopt::Long;
 my @getopt_args = (
     'a',       # content i/o in text(ascii) mode
     'm=s',     # set method
@@ -558,3 +517,44 @@ Usage: $progname [-options] <url>...
     -h            Print this message
 EOT
 }
+
+# We make our own specialization of LWP::UserAgent that asks for
+# user/password if document is protected.
+{
+
+    package RequestAgent;
+
+    use strict;
+    use warnings;
+    use base qw(LWP::UserAgent);
+
+    sub new {
+        my $self = shift->SUPER::new(@_);
+        $self->agent("lwp-request/$LWP::VERSION ");
+        $self;
+    }
+
+    sub get_basic_credentials {
+        my ($self, $realm, $uri) = @_;
+        if ($options{'C'}) {
+            return split(':', $options{'C'}, 2);
+        }
+        elsif (-t) {
+            my $netloc = $uri->host_port;
+            print STDERR "Enter username for $realm at $netloc: ";
+            my $user = <STDIN>;
+            chomp($user);
+            return (undef, undef) unless length $user;
+            print STDERR "Password: ";
+            system("stty -echo");
+            my $password = <STDIN>;
+            system("stty echo");
+            print STDERR "\n";    # because we disabled echo
+            chomp($password);
+            return ($user, $password);
+        }
+        else {
+            return (undef, undef);
+        }
+    }
+}
```

**Comment by fany** [comment]
> On an aesthetics note, would moving the class of to the bottom like this look better in the end?

Probably.  I just tried to change as little code as possible to make it work again.

**Comment by karenetheridge** [comment]
I would prefer to keep the diff small, as the placement of the package is of not great consequence to readability.

**Comment by oalders** [comment]
LGTM

**Comment by oalders** [comment]
Thanks @fany for the patch and thanks to @genio for putting the work into confirming the fix!

**Pull request merged**
